<a href="https://colab.research.google.com/github/lamihaA/INTERNSHIP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [5]:
df=pd.read_csv('/content/nlp_dataset.csv')
print(df)

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [12]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [13]:
stop_words = set(stopwords.words('english'))
print(stop_words)
lemmatizer = WordNetLemmatizer()

{'weren', 'by', "you've", 'there', "mightn't", 'both', 'so', 'am', 've', 'about', "i've", "should've", 'who', 'd', "didn't", 'couldn', 'once', "you'll", 's', 'above', 'himself', 'more', "that'll", 'very', "mustn't", 'didn', "he's", "we'll", 'that', 'from', 'i', 'out', 'shan', 'mustn', 'before', 'off', "we'd", 'where', 'your', 'doing', 'while', 'too', 'here', 'had', "she'd", "won't", 'be', 'can', 'shouldn', 'nor', 'was', 'ours', 'same', "it'd", 'further', 'is', "aren't", 'whom', 'how', 'below', 'than', 'with', "shan't", 'those', 'm', "they'd", 'because', 'him', "she'll", "doesn't", 'down', "we've", 'he', 'its', 'their', "they'll", "hadn't", 'into', 'few', 'only', 'should', "shouldn't", 'if', 'them', 'these', "i'd", 'between', 'own', 'against', 'her', 'they', "they've", "you'd", 'over', 'ain', 'o', "wouldn't", 'we', 'after', 'been', 'such', 'all', 'and', 'themselves', 'y', 'at', 'will', 'his', 'having', 'won', 'yours', "isn't", 'll', 'just', 'until', 'when', "don't", 'then', 're', 'hadn', 'has', 'which', 'theirs', "it's", "we're", 'did', 'herself', 'why', 'she', 'not', 'during', 'to', 'no', 'most', 'in', 'have', 'itself', 'wasn', 'an', "he'd", 'up', 'a', 'yourself', "she's", "you're", "couldn't", 'does', 'are', 'on', "i'm", 'our', 'aren', 'for', 'the', 'through', 'yourselves', 'were', 'under', 'you', 'mightn', 'wouldn', 'as', "i'll", 'isn', 'now', 'me', 'hasn', 'other', 'any', 'ourselves', 'haven', 'hers', 'or', 'myself', 'this', "wasn't", "weren't", 'but', 'being', 'needn', 't', 'again', 'my', "needn't", 'of', "he'll", "hasn't", 'some', "they're", 'it', 'each', 'what', 'ma', 'doesn', 'do', 'don', "haven't", "it'll"}

In [24]:
def process_text(text):
  word_tokens = word_tokenize(text)
  filtered_tokens = [word for word in word_tokens if word.lower() not in stop_words]
  lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
  return {
      "Original_Text": text,
      "Word_Tokens": word_tokens,
      "Filtered_Tokens": filtered_tokens,
      "Lemmatized_Tokens": lemmatized_tokens
  }

In [25]:
result=df['Text'].apply(process_text)
processed_df=pd.DataFrame(result.tolist())
print(processed_df.head)

<bound method NDFrame.head of                                        Original_Text  ...                                  Lemmatized_Tokens
0  Natural Language Processing is a fascinating f...  ...  [Natural, Language, Processing, fascinating, f...
1  It bridges the gap between humans and machines...  ...  [bridge, gap, human, machine, enabling, comput...
2  NLP techniques are widely used in applications...  ...  [NLP, technique, widely, used, application, ch...
3  Machine translation and speech recognition are...  ...  [Machine, translation, speech, recognition, co...
4  Despite its advancements, NLP faces challenges...  ...  [Despite, advancement, ,, NLP, face, challenge...
5  Continuous research and innovation are improvi...  ...  [Continuous, research, innovation, improving, ...
6  The potential of NLP is vast, making it essent...  ...  [potential, NLP, vast, ,, making, essential, m...

[7 rows x 4 columns]>

In [28]:
processed_file_path='/content/nlp_dataset.csv'
processed_df.to_csv(processed_file_path, index=False)

In [30]:
df

                                       Original_Text  ...                                  Lemmatized_Tokens
0  Natural Language Processing is a fascinating f...  ...  ['Natural', 'Language', 'Processing', 'fascina...
1  It bridges the gap between humans and machines...  ...  ['bridge', 'gap', 'human', 'machine', 'enablin...
2  NLP techniques are widely used in applications...  ...  ['NLP', 'technique', 'widely', 'used', 'applic...
3  Machine translation and speech recognition are...  ...  ['Machine', 'translation', 'speech', 'recognit...
4  Despite its advancements, NLP faces challenges...  ...  ['Despite', 'advancement', ',', 'NLP', 'face',...
5  Continuous research and innovation are improvi...  ...  ['Continuous', 'research', 'innovation', 'impr...
6  The potential of NLP is vast, making it essent...  ...  ['potential', 'NLP', 'vast', ',', 'making', 'e...

[7 rows x 4 columns]

In [32]:
print(f"Processed data saved to {processed_file_path}")

Processed data saved to /content/nlp_dataset.csv

In [31]:
result

0    {'Original_Text': 'Natural Language Processing...
1    {'Original_Text': 'It bridges the gap between ...
2    {'Original_Text': 'NLP techniques are widely u...
3    {'Original_Text': 'Machine translation and spe...
4    {'Original_Text': 'Despite its advancements, N...
5    {'Original_Text': 'Continuous research and inn...
6    {'Original_Text': 'The potential of NLP is vas...
Name: Text, dtype: object